### ISSUE TITLE
Release 1.4.1

### ISSUE THREAD

**Issue by rogerhu** [BottleRocketApps/Android-Vault#12]
Can you release v1.4.1 to Bintray? https://bintray.com/bottlerocketapps/maven/com.bottlerocketstudios.vault/view

**Comment by rogerhu** [comment]
Anyone home?  :)  

I'm happy to add a Bintray plugin to this project if it would help expedite the release process.

**Comment by nathanoneal** [comment]
Hi Roger,

1.4.2 should be available now. Thanks for your patience!
